use a gemstash container based on alpine (provided by govuk)
It is one order of magnitude smaller than the one built on top of
ruby:2.5.1 (like, 60M instead of 600M)

diff --git a/containers/gemstash/Dockerfile b/containers/gemstash/Dockerfile
--- a/containers/gemstash/Dockerfile
+++ b/containers/gemstash/Dockerfile
@@ -1,7 +1,52 @@
-FROM ruby:2.5.1
+FROM alpine:3.6.5
+
+RUN apk update \
+    # Things we need in order to build ruby
+    && apk add --no-cache --virtual .ruby-builddeps \
+        autoconf \
+        bison \
+        bzip2 \
+        bzip2-dev \
+        ca-certificates \
+        coreutils \
+        gcc \
+        gdbm-dev \
+        glib-dev \
+        libc-dev \
+        libffi-dev \
+        libxml2-dev \
+        libxslt-dev \
+        linux-headers \
+        make \
+        ncurses-dev \
+        libressl \
+        libressl-dev \
+        procps \
+        readline-dev \
+        ruby \
+        tar \
+        xz \
+        yaml-dev \
+        zlib-dev \
+    # Things we need to run the container
+    && apk add --no-cache --virtual .ruby-rundeps \
+        curl \
+        ruby \
+        ruby-dev \
+        sqlite-dev \
+        ruby-io-console \
+        ruby-json \
+    # Get gemstash
+    && gem install --no-ri --no-rdoc gemstash \
+    # Clean up build dependencies
+    && apk del .ruby-builddeps
+
+EXPOSE 9292
+
+HEALTHCHECK --interval=15s --timeout=3s\
+        CMD curl -f http://localhost:9292/ || exit 1
 
 RUN mkdir -p /var/cache/gem
-RUN gem install --no-ri --no-rdoc -v 2.0.0 gemstash
 COPY config.yml /etc/gemstash.yml
-
 CMD ["gemstash", "start", "--no-daemonize", "--config-file", "/etc/gemstash.yml"]
+
